name:       APNG
category:   Interface
tags:       [animation, canvas]
demo:       http://devthought.com/projects/mootools/APNG/
demo:       http://devthought.com/wp-content/projects/mootools/APNG/Demo/