name:       APNG
author:     rauch
category:   Interface
tags:       [animation, canvas]
docs:       http://devthought.com/projects/mootools/APNG/
demo:       http://devthought.com/wp-content/projects/mootools/APNG/Demo/